version: '3.3'

volumes:
  rabbit_data:
  
services:
 web:
   image: python:3.8
   command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
   volumes:
     - .:/code
   ports:
     - 8000:8000
   working_dir: /code

 cel:
   image: python:3.8
   command: sh -c "celery -A proj worker -l info"
   volumes:
     - .:/code
   working_dir: /code
   depends_on:
     - rabb
     
 rabb:
   image: rabbitmq
   volumes:
     - rabbit_data:/var/lib/rabbitmq
   ports:
     - 5671:5671
     - 15672:15672